GET http://localhost:5000/users

###

POST http://localhost:5000/users/new
Content-Type: application/json

{
  "login": "Adam",
  "password": "1234",
  "mail": "mail@m.com",
  "role": "Szefu"
}

###

DELETE  http://localhost:5000/users/delete/62be117f825346329c617b42
